version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      svelte-packages:
        patterns:
          - "svelte*"
          - "@sveltejs/*"
      dev-dependencies:
        dependency-type: "development"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "automerge-candidates" 