name: CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - run: npm ci

      - run: npx prettier --write .

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Format code with Prettier' || echo "No changes to commit"
          git push

  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - run: npm ci

      - run: npm run check

      - run: npm run lint

      - run: npm run build

      - name: Set up environment variables
        run: echo "GPT_API_KEY=${{ secrets.GPT_API_KEY }}" >> $GITHUB_ENV

      - uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: build
          single-commit: true
